environment = "dev"
location = "East US"
backend_resource_group_name = "dev_backend_storage_account_rg"
backend_storage_account_name = "dev_backend_storage_account_name"
backend_container_name = "dev_backend_storage_account_container"